server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/rdijin/rdiforest/workspace/configrepo
          uri: https://github.com/Wordbe/spring-cloud-config
          default-label: main